{{- if .Values.besuConfig.permissions.nodes.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "besu.fullname" . }}-node-permissions-configmap
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
data:
  nodes-allowlist.yml: |-
    nodes-allowlist=[
      "{{ .Values.network.bootnode.enode }}",
      "enode://{{ trimPrefix "0x" .Values.validators.validator1.publicKey }}@{{ template "besu.fullname" . }}-validator1-0.{{ template "besu.fullname" . }}-validator1.{{ .Values.namespace }}.svc.cluster.local:30303",
    ]
{{- end -}}
