apiVersion: v1
kind: Service
metadata:
  name: {{ template "besu.fullname" . }}-node-udp
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: node
    namespace: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ template "besu.name" . }}
    release: {{ .Release.Name }}
    component: node
  ports:
    - name: discovery
      port: {{ .Values.besuConfig.p2p.port }}
      targetPort: discovery
      protocol: UDP