apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "besu.fullname" . }}-prometheus-configmap
  labels:
    app: {{ template "besu.fullname" . }}-prometheus-configmap
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
data:
  prometheus.yml: |-
{{ .Files.Get "prometheus.yml" | indent 4}}