apiVersion: v1
kind: Service
metadata:
  name: {{ template "besu.fullname" . }}-prometheus
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace }}
    component: prometheus
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    component: prometheus
  ports:
    - port: 9090
      protocol: TCP
      name: prometheus